// Code generated by "stringer -type Command"; DO NOT EDIT.

package epd

import "fmt"

const _Command_name = "DriverOutputControlBoosterSoftStartControlGateScanStartPositionDeepSleepModeDataEntryModeSettingSwResetTemperatuteSendorControlMasterActivationDisplayUpdateControl1DisplayUpdateControl2WriteRAMWriteVCOMRegisterWriteLUTRegisterSetDummyLinePeriodSetGateTimeBorderWaveformControlSetRamXAddressStartEndPositionSetRamYAddressStartEndPositionSetRamXAddressCounterSetRamYAddressCounterTerminateFrameReadWrite"

var _Command_map = map[Command]string{
	1:   _Command_name[0:19],
	12:  _Command_name[19:42],
	15:  _Command_name[42:63],
	16:  _Command_name[63:76],
	17:  _Command_name[76:96],
	18:  _Command_name[96:103],
	26:  _Command_name[103:127],
	32:  _Command_name[127:143],
	33:  _Command_name[143:164],
	34:  _Command_name[164:185],
	36:  _Command_name[185:193],
	44:  _Command_name[193:210],
	50:  _Command_name[210:226],
	58:  _Command_name[226:244],
	59:  _Command_name[244:255],
	60:  _Command_name[255:276],
	68:  _Command_name[276:306],
	69:  _Command_name[306:336],
	78:  _Command_name[336:357],
	79:  _Command_name[357:378],
	255: _Command_name[378:401],
}

func (i Command) String() string {
	if str, ok := _Command_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Command(%d)", i)
}
